ci

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -20,6 +20,11 @@ jobs:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
+      - name: check file Dockerfile
+        run: |
+          ls -l
+          ls -l ToDoApp || echo "not found ToDoApp"
+
       - name: Build Docker image
         run: |
           cd ToDoApp
